# Generated by Django 5.1.5 on 2025-02-09 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish_Image', models.ImageField(upload_to='Dish_Images/')),
                ('Dish_Name', models.CharField(max_length=100)),
                ('Dish_Quantity', models.CharField(choices=[('Full', 'Full'), ('Half', 'Half')], default='Full', max_length=4)),
                ('Dish_Price', models.PositiveIntegerField()),
                ('Dish_Food_Type', models.CharField(choices=[('Chicken', 'Chicken'), ('Mutton', 'Mutton'), ('Veg', 'Veg')], max_length=7)),
                ('Dish_Type', models.CharField(choices=[('Mian Course', 'Main Course'), ('Starter', 'Starter'), ('Sweet', 'Sweet'), ('Cold Drink', 'Cold Drink'), ('Roti', 'Roti')], max_length=11)),
                ('Dish_Information', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Employe_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employe_Name', models.CharField(max_length=100)),
                ('Employe_Number', models.CharField(max_length=10, unique=True)),
                ('Employe_Address', models.CharField(max_length=1000)),
                ('Employe_Position', models.CharField(choices=[('waiter', 'waiter'), ('cook', 'cook'), ('Other', 'Other')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Table_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_served', to='Pos_Main_App.employe_model')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedDish_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_dishes', to='Pos_Main_App.bill_model')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pos_Main_App.dishes_model')),
            ],
        ),
        migrations.AddField(
            model_name='bill_model',
            name='dishes',
            field=models.ManyToManyField(related_name='bills', through='Pos_Main_App.OrderedDish_model', to='Pos_Main_App.dishes_model'),
        ),
        migrations.AddField(
            model_name='bill_model',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='Pos_Main_App.table_model'),
        ),
    ]
