# Generated by Django 5.1.5 on 2025-02-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos_Main_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes_model',
            name='Dish_Type',
            field=models.CharField(choices=[('Main Course', 'Main Course'), ('Starter', 'Starter'), ('Sweet', 'Sweet'), ('Cold Drink', 'Cold Drink'), ('Roti', 'Roti')], max_length=11),
        ),
    ]
