# Generated by Django 5.1.5 on 2025-02-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pos_Main_App', '0002_alter_dishes_model_dish_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_model',
            name='customer_name',
        ),
    ]
