# Generated by Django 5.1.6 on 2025-03-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pos_Main_App', '0004_contactsupport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsupport',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contactsupport',
            old_name='address',
            new_name='user_message',
        ),
        migrations.RemoveField(
            model_name='contactsupport',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='contactsupport',
            name='pin_code',
        ),
    ]
